apiVersion: v1
kind: Pod
metadata:
  name: todo-app
spec:
  containers:
  - name: todo-app
    image: sameer27488/todo-app-gitops:42bc2be78db9c77ec6e7dda9618a74fb86811cee
    ports:
    - containerPort: 80