apiVersion: v1
kind: Pod
metadata:
  name: todo-app
spec:
  containers:
  - name: todo-app
    image: sameer27488/todo-app-gitops:47d6dd461303b587f91e6c38eb88d9b101875e21
    ports:
    - containerPort: 80